[package]
name = "two_dimensional_sdf"
version = "0.1.0"
edition = "2018"

[lib]
path = "two_dimensional_sdf.rs"

[dependencies]
shader_roy_metal_sl_interface = { path="../../shader_roy_metal_sl_interface" }

