[package]
name = "example_raymarching"
version = "0.1.0"
authors = ["Michal Srb <xixixao@seznam.cz>"]
edition = "2018"

[lib]
path = "src/example_raymarching.rs"

[dependencies]
shader_roy_metal_sl_interface = { path="../shader_roy_metal_sl_interface" }

